### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by jcward** [jcward/vscode-haxe#1]
VSCode docs: https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition

![image](https://cloud.githubusercontent.com/assets/2192439/11856761/4fb2c2cc-a410-11e5-8266-ef5e3b792cf2.png)

Haxe code completion: http://haxe.org/manual/cr-completion-overview.html

It has "position" (jump to definition), regular completion, and more.

**Comment by lewislepton** [comment]
ill just add to this instead of a new post

what i was meaning on twitter regarding the 'terminal runner' is to try and cut that out. rather than having terminal/command line open asd using 'haxe --wait 6000'. instead it would just be working within vscode.

this is what im going to try and look into tomorrow

**Comment by jcward** [comment]
Gotcha. So the reason this is this way is because a library to handle this capability (starting, communicating with, maintaining, and stopping the haxe completion server process) is a work in progress over at http://github.com/SnowKit/Tides

Starting the server isn't the hard part - the code's already there. But making sure it works across win/mac/linux and then killing it at the right time could prove more difficult.

Still, if you're dying to take a crack at it, feel free. :)

**Comment by lewislepton** [comment]
damn. yeah. remember now. ill still have a look. may as well ;)

**Comment by pleclech** [comment]
In the actual version it is started and close automatically, you can change globally the haxe configuration in package,json (https://github.com/jcward/vscode-haxe/blob/master/package.json#L49) or by project creating a .vscode folder and put your settings here. See https://code.visualstudio.com/docs/customization/userandworkspace?utm_expid=101350005-9._kM5PDapS5KdYQ0OiWM-yQ.0&utm_referrer=https%3A%2F%2Fcode.visualstudio.com%2Fdocs%2Flanguages%2Foverview

**Comment by jcward** [comment]
@pleclech - are you saying that, with your changes, it will start the haxe server?

**Comment by pleclech** [comment]
yes you did not have seen it , ooops ;)
https://github.com/jcward/vscode-haxe/blob/b313ba0fd29ef2978ac4a92b840987b35b47bfb9/src/HaxeContext.hx#L89

**Comment by pleclech** [comment]
it trys to connect on the designated por and address if is ok, nothing change.
If it can connect on the port but it's not a haxe server, it tries another port until it succeed.
if it cant connect, it trys to launch a server , if the port is already used it repeat again but with another port.
If the server was launched by the application, it will also be killed on exit.

**Comment by jcward** [comment]
I'm going to go ahead and close this issue, basic code completion has been done for a long time. :)
