### ISSUE TITLE
Works on Ubuntu 14.04

### ISSUE THREAD

**Issue by ashes999** [jcward/vscode-haxe#12]
This [VS2015 Voice issue](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7756341-haxe-support?tracking_code=00955d37f0d4f590d828e97730574249) got a comment today saying "the community is handling this, please help them or help us help them."

I got this working today on Linux. I just want to say thanks. After a couple of years of fiddling around with Haxe (mostly on Linux), I finally have code-completion.

Great work!!

**Comment by jcward** [comment]
Excellent, thanks for the feedback. I didn't realize that voice issue had so many comments / votes - cool! VSCode is very slick, and Haxe's completion engine is awesome. Using both together makes learning Haxe (and new libraries) so much faster!

**Comment by ashes999** [comment]
Caveat: this doesn't work 100% (as you stated in the README). I'm having a hard time figuring out exactly what does and doesn't work.

What clearly works, is accessing core haxe APIs (most of the type) -- like typing `sys.io.File.` + `CTRL+Space` gives me a list of methods.

Typing `this.` doesn't give me anything reasonable for auto-complete. 

Hopefully, some of these things will improve over time. Let me know if you need help testing on Ubuntu.

**Comment by jcward** [comment]
@ashes999 hmm, `this.` completion seems to work for me:

![image](https://cloud.githubusercontent.com/assets/2192439/13531231/bbf36828-e1e2-11e5-804a-f80bd3448edc.png)

You can debug the completion server if you (first kill any existing completion servers and then) start the completion server in a  terminal by hand:

```
>pkill haxe
>haxe -v --wait 6000
```

Perhaps there's an syntax error that's throwing it off?

**Comment by ashes999** [comment]
You're on to something. `pkill haxe` showed that I had two `haxe` instances running. Killing those off fixed auto-completion for `this.`.

BUT, I noticed quitting VSCode didn't kill the haxe server. This explains how I had two copies already running in the background.

Thoughts?

BTW, I don't have compilation errors -- I'm testing a "good" code state just to get VSCode working.

**Comment by jcward** [comment]
> I noticed quitting VSCode didn't kill the haxe server.

Yep, it's filed here: https://github.com/jcward/vscode-haxe/issues/3 ;)

**Comment by ashes999** [comment]
Okay, thanks. I'll let this issue die in peace, then :)
