### ISSUE TITLE
Function signature completion doesn't always work

### ISSUE THREAD

**Issue by jcward** [jcward/vscode-haxe#14]
I know this has to do with tricky parsing (in lieu of support from the compiler.)

For example, this works:
![image](https://cloud.githubusercontent.com/assets/2192439/13637510/f2134294-e5c4-11e5-97b2-ba6189e3e452.png)

And this works:
![image](https://cloud.githubusercontent.com/assets/2192439/13637583/546e9966-e5c5-11e5-848b-67b13cddb197.png)

But this doesn't:
![image](https://cloud.githubusercontent.com/assets/2192439/13637543/1ea3dbac-e5c5-11e5-997f-bb952c7641d7.png)

It's probably that literal string.

**Comment by jcward** [comment]
Hey, @pleclech - thanks for the fix! Is it known that function signature completion seems to only work with the Haxe tmp directory enabled? That's not terrible -- perhaps I'll note it in the docs. Or we could attempt to auto-locate a suitable temp directory per platform. (/tmp/.vscode, ~/.vscode/haxe-tmp/ or something...)

**Comment by pleclech** [comment]
@jcward Yep, to avoid figthing with parsing too many case for function argument i inject a macro into at the coma place so this is why a tmp directory is neede ;)
If we can autodetect why not , yes. To avoid messing with two directories the one setted into the config have to override the one autodetected

**Comment by jcward** [comment]
Sounds good, filed new enhancement #18 -- I might be able to get to do this one. :)

**Comment by pleclech** [comment]
@jcward  Nice :+1:
