### ISSUE TITLE
Formatting Document doesn't work

### ISSUE THREAD

**Issue by ashes999** [jcward/vscode-haxe#16]
According to [this SO question](http://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode) and it's various answers, there should be ways to get formatting to work on VSCode.

[One of these answers](http://stackoverflow.com/a/30031398/210780) suggests that this only works for supported languages. [A comment on it](http://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode#comment53627072_30031398) suggests that there's a list of supported languages.

For Haxe, this makes it seem like we need to do something with `vscode-haxe` to get document formatting to work.  Is that the case?

NB: none of the various work-arounds work; I've tried (on Ubuntu):
- `CTRL`+`SHIFT`+`I`
- The old/depcreated `SHIFT+ALT+F`
- Assigning a custom key-binding for `CTRL+K, CTRL+D`

**Comment by jcward** [comment]
Note, if I open a JavaScript file, CTRL-SHIFT-I "beautifies" the buffer on Ubuntu. As you state, this does not work for a .hx file (though it is syntax highlighting it.) I don't know exactly provides this behavior. Perhaps it has to do with implementing the `Languages.registerDocumentFormattingEditProvider` API.

**Comment by jcward** [comment]
I'm going to close this - CTRL-SHIFT-I will not be implemented in this plugin. Feel free to migrate to the newer [vshaxe plugin](https://github.com/vshaxe/vshaxe) ([marketplace link](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe)).
