### ISSUE TITLE
using build.hxml to generate two different targets confuses VSCODE

### ISSUE THREAD

**Issue by MatthijsKamstra** [jcward/vscode-haxe#28]
example build.hxml

```
-cp src
-main Main
-php bin/www

--next

-cp src
-main MainJS
-js bin/javascript.js
```

php code works like expected
js code gives errors
for example:

```
    private var _doc = js.Browser.document;
```

![screen shot 2016-04-13 at 13 32 44](https://cloud.githubusercontent.com/assets/907219/14491953/427d4a86-017c-11e6-9be3-8e88d8df96a1.png)

**Comment by pleclech** [comment]
@MatthijsKamstra
Working at the moment to see if a build/target selection can be implemented for completion,
But you will have to choose on wich target you are working on ;)

**Comment by MatthijsKamstra** [comment]
awesome!

**Comment by jcward** [comment]
I'm going to close this for now... Multiple targets seems a little bit of an edge case to me, especially as this project is in "legacy / support" mode.
