### ISSUE TITLE
Completion server isn't stopped (on Linux, haven't tested Mac/Win)

### ISSUE THREAD

**Issue by jcward** [jcward/vscode-haxe#3]
@pleclech: On linux, if I open code and it starts the completion server automatically, I tried closing the project, then closing code. The completion server is still running.

I'm not sure if the `dispose()` function I was prototyping (https://github.com/jcward/vscode-haxe/blob/master/src/HaxeContext.hx#L118) actually ever gets run, and I think that's where you put the cleanup logic?

**Comment by pleclech** [comment]
yes it's where i kill the server (https://github.com/jcward/vscode-haxe/blob/master/src/HaxeContext.hx#L132).
You can put a breakpoint and see if it is reached. I have to setup a linux VM to test it
On windows (seven) where i test it, it works, the call is made and server killed.

**Comment by pleclech** [comment]
I have just tested it on an ubuntu 12.01 VM virtualbox and didn't see any problem the process is killed when vscode is closed...strange.

**Comment by jcward** [comment]
Very strange. The process definitely hangs around after closing code for me:

![image](https://cloud.githubusercontent.com/assets/2192439/12236899/592a6304-b839-11e5-9440-44e962a45e14.png)

Oddly, it's also not stopping at my breakpoints:

![image](https://cloud.githubusercontent.com/assets/2192439/12237131/6f6dbe44-b83a-11e5-8b6b-048aaa76c96e.png)

Is it not source mapped? Do I need to set the breakpoint in the haxe.js code?

**Comment by jcward** [comment]
Ok, setting breakpoints in haxe.js works. I get to the breakpoint where .haxeProcess is created, with the right PID, but never hit where it's killed...  hmm.

**Comment by pleclech** [comment]
Don't know if it's releated https://github.com/Microsoft/vscode/issues/1298
otherwise if you put a trace into the dispose function do you see it ?

**Comment by ashes999** [comment]
+1 I also see this on my Ubuntu box

**Comment by pleclech** [comment]
@jcward can you check if it solve the killing problem on linux : https://github.com/pleclech/vscode-haxe/tree/master

**Comment by jcward** [comment]
@pleclech Hmm, no it didn't help. And I made sure I was on master branch with your "killing haxe server" commit.

**Comment by pleclech** [comment]
@jcward humm, can you check if the process pid is well setted and has the same value as when you do a 'ps' ?

**Comment by jcward** [comment]
@pleclech Yep, same PID the whole time:
![image](https://cloud.githubusercontent.com/assets/2192439/13548547/1dfe0e4c-e2b0-11e5-82bb-e6242f8946f8.png)
![image](https://cloud.githubusercontent.com/assets/2192439/13548549/22d463c6-e2b0-11e5-8903-79684b0a7138.png)

**Comment by pleclech** [comment]
@jcward How the kill -9 PID could fail, unless it not called, one way to be sure , may be touch a file when dispose is called ?

**Comment by jcward** [comment]
@pleclech - yes, dispose is not getting called, this file is not created (same code I put elsewhere did):

![image](https://cloud.githubusercontent.com/assets/2192439/13548688/1d26003a-e2b3-11e5-8d2a-83c31ce725ff.png)

**Comment by jcward** [comment]
@pleclech @ashes999 Upgrading VSCode fixed the problem (download latest [here](https://code.visualstudio.com/)). 0.10.1 suffers from the problem, 0.10.8 works. I'm going to check master, then close this issue.

**Comment by jcward** [comment]
Current master branch works fine under 0.10.8 - sorry for the wild goose chase, cheers!

**Comment by ashes999** [comment]
That's great. I'll upgrade/verify and let you know.

Are you planning to push a new version to the Marketplace?

**Comment by pleclech** [comment]
Cool :)

**Comment by ashes999** [comment]
I also installed VS Code ages ago. I'll update and report back if I see the `haxe` processes kicking around.

**Comment by ashes999** [comment]
Confirmed: upgrading from 0.10.3 to 0.10.10 fixed this for me, too. Thanks for tracking this down!
