### ISSUE TITLE
No code completion?

### ISSUE THREAD

**Issue by mikeevmm** [jcward/vscode-haxe#35]
Hi, I've been loving VSCode and was looking forward to using it with haxe.

Syntax highlighting seems to be working fine with the plugin installed, but I can't seem to get any code recognition/hinting/completion whatsoever.

Using Windows 10, Haxe 3.2.1.

**Comment by mikeevmm** [comment]
Running `haxe -v --wait 6000` in a terminal just hangs waiting for a connection.

**Comment by mikeevmm** [comment]
Using the repo code directly didn't seem to help either.

**Comment by jcward** [comment]
Hmm, what version of VSCode is it? What's your directory / file structure -- do you have a `build.hxml` file in the folder you open in VSCode?

**Comment by mikeevmm** [comment]
I have a `Project.xml`, but I adjusted `Settings.json` to

``` json
// Place your settings in this file to overwrite default and user settings.
{
    "haxe.haxeDefaultBuildFile": "Project.xml",
    "haxe.haxeVSCodeBuildFile": "vscode-project.xml"
}
```

Using the most recent version of VSCode --- where can I check the actual version? _EDIT:_ 1.5.2

(Also, don't quote me on this, but I think haxe has officially moved to `.xml`s, leaving `.hxml`?)

**Comment by jcward** [comment]
Ah -- is Project.xml a project file for OpenFL or perhaps HaxeFlixel? The plugin needs an hxml file. There are some notes on generating an hxml file for various frameworks at: https://github.com/jcward/vscode-haxe#framework-notes -- let me know if that gets you going.

**Comment by mikeevmm** [comment]
Ah, I keep getting mixed up with deprecated stuff vs pipeline :) Thank you for the fast help, will update!

**Comment by mikeevmm** [comment]
Nope, created a `build.hxml` as described in https://github.com/jcward/vscode-haxe#framework-notes , still no autocompletion.

build.hxml:

```
-main ApplicationMain 
-cp E:/HaxeToolkit/haxe/lib/flixel/4,1,1
-D flixel=4.1.1
-cp E:/HaxeToolkit/haxe/lib/openfl/3,6,1
-D openfl=3.6.1
-cp E:/HaxeToolkit/haxe/lib/lime/2,9,1
-D lime=2.9.1
--macro keep('IntIterator')
-cp E:/HaxeToolkit/haxe/lib/hscript/2,0,7
-D hscript=2.0.7
-cp source
-cp E:\HaxeToolkit\haxe\lib/openfl/3,6,1/extern
-D HXCPP_QUIET
-D openfl-next
-D tools=2.9.1
-D FLX_NO_DEBUG
-D no-compilation
-D NAPE_RELEASE_BUILD
-D native
-D FLX_NO_TOUCH
-D lime-native
-D openfl-native
-D windows
-D desktop
--remap flash:openfl
--macro flixel.system.macros.FlxDefines.run()
-cp export/windows/cpp/haxe
-cpp export/windows/cpp/obj
--macro keep("Main")
-D display
```

**Comment by BreadSniper** [comment]
Same issue here, the extension was working for me before, but I guess it broke after one of the VSCode updates. Using VSCode on Mac, Haxe 3.2.1

**Comment by mikeevmm** [comment]
Thank you :)
