### ISSUE TITLE
osx autocompletion strange behaviour 

### ISSUE THREAD

**Issue by MatthijsKamstra** [jcward/vscode-haxe#7]
I have strange behaviour on osx with autocompletion.

A short example:
![hxcode](https://cloud.githubusercontent.com/assets/907219/13027697/7a5caa2a-d259-11e5-95e0-cb45069aa7fb.gif)

I use the arrows to select, confirm with return (the first time) and with tab (second example).

I don't know if it has something to do with the haxe plugin, VSC or a setting.

**Comment by jcward** [comment]
Huh, that is strange. As a UI/keyboard input issue, I'd suspect vscode, but I don't see any relevant issues in their repo. Maybe try a different language extension and see how it works?

I'll see if I can reproduce on a Mac here, but it'll be a while before I can get it to.

**Comment by MatthijsKamstra** [comment]
Hi Jeff, 
I revisited this issue and the update fixed the problem
https://code.visualstudio.com/updates#vscode

> 0.10.9 (January 2016)
> The 0.10.9 release addresses an issue with indentation and the Tab key on OS X.

**Comment by jcward** [comment]
@MatthijsKamstra great, thanks for the update!
