### ISSUE TITLE
99+ error from Context.hx

### ISSUE THREAD

**Issue by MatthijsKamstra** [jcward/vscode-haxe#8]
don't know how it starts, but I have had this a couple of times:

Context.hx /usr/local/lib/haxe/macro

I can open the file (which is awesome btw!) but there is no error after I force to update the file (change the file, which is not possible, so discard and this error is gone)
but I still have 99 errors message at the bottom of the page.

![screen shot 2016-02-26 at 10 27 06](https://cloud.githubusercontent.com/assets/907219/13348385/81aa829c-dc73-11e5-90dc-1e77b7c32cd6.png)

on osx 

btw restart vscode fixes everything

**Comment by jcward** [comment]
How odd. I've never seen this, and am not really familiar with macro/Context.hx. Is it something related to macros? Maybe @pleclech has some insight?

**Comment by pleclech** [comment]
Euh  no, no idea is the project available somewhere ?

**Comment by MatthijsKamstra** [comment]
I thought I had something to do with computer falling "asleep", but I can't reproduce it.
Will keep a close look out for it perhaps I can recognize a pattern.

@pleclech  it's not with a specific project, I have had it with three different code bases. 
@jcward I don't do macros, so it must be something haxe compiler uses?

**Comment by jcward** [comment]
Closing as stale, feel free to post more details.
